name: another test workflow
on:
    push:

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: checkout composite
              uses: actions/checkout@v4
              with:
                repository: NeilluANZx/neil-test-repo-a
                path: ./.actions
            - uses: ./.actions/composite
            