name: another test workflow
on:
    push:

jobs:
    test-job:
        uses: NeilluANZx/neil-test-repo-a/.github/workflows/test.yml@main
    
    second-job:
        uses: NeilluANZx/neil-test-repo-a/.github/workflows/test.yml@main