name: another test workflow
on:
    push:

jobs:
    test-job:
        uses: NeilluANZx/neil-test-repo-a/.github/workflows/test.yml@main

    second-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: Test step
              run: echo "Hello world"

    third-job:
        needs: second-job
        uses: NeilluANZx/neil-test-repo-a/.github/workflows/test.yml@main